([
	{
		shouldDeps: [
			{ block: 'avatar' },
			{ block: 'avatar', elem: 'photo', mods: { size: ['xs', 's', 'm', 'l'] } },
			
			{ block: 'badge', mods: { view: ['default', 'success', 'warning', 'alert'] } },

			{ block: 'brand-logo', mods: { form: ['mask', 'round'],
										   size: ['xxs', 'xs', 's', 'm', 'l', 'xl'] } },
			
			{ block: 'decorator', mods: { 'indent-a': ['auto', 'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-b': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-h': ['auto', 'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-l': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-r': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-t': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'indent-v': ['auto', 'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-a': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-b': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-h': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-l': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-r': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-t': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'],
										  'space-v': [		   'xxxs', 'xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl', 'xxxxxl', 'xxxxxxl'] } },

			{ block: 'icon', mods: { size: ['s', 'm'], 
									 view: ['alert', 'disable', 'ghost', 'primary', 'secondary', 'success', 'warning'] } },

			{ block: 'social-icon', mods: { hover: 'default',
											size: 'm',
											view: ['alert', 'brand', 'disable', 'ghost', 'primary', 'secondary', 'success'] } },

			{ block: 'tag', mods: { size: ['s', 'm'],
									view: ['default', 'disable', 'link'] } },
			{ block: 'tag', elem: 'text' },

			{ block: 'text', mods: { align: ['center', 'left', 'right'],
									 decoration: ['underline'],
									 display: ['block', 'inline-block', 'inline'],
									 size: ['s', 'xs', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
									 spacing: ['m', 's', 'xs'],
									 style: ['italic'],
									 transform: ['uppercase'],
									 type: ['blockquote', 'h1', 'h2', 'h3', 'p'],
									 view: ['alert', 'brand', 'disable', 'ghost', 'income', 'letter', 'link-minor', 'link', 'primary', 'promo', 'secondary', 'success'],
									 weight: ['black', 'bold', 'light', 'regular', 'semibold', 'thin'],
									 width: ['default'] } },

			{ block: 'theme', mods: { breakpoint: ['default'],
									  color: ['whitepaper-brand', 'whitepaper-default', 'whitepaper-inverse'],
									  font: ['ibm', 'museo'],
									  gap: ['large', 'medium', 'small'],
									  menu: ['default'],
									  size: ['default'],
									  space: ['default'] } },

			{ block: 'pt-card', mods: { border: ['all'],
										shadow: ['cloud'],
										view: ['default'] } },
			{ block: 'pt-card', elem: 'content', mods: { align: ['center', 'right'],
														'space-a': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-b': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-h': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-l': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-r': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-t': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-v': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'vertical-align': ['center'] } },
			{ block: 'pt-card', elem: 'footer', mods: { 'align': ['bottom', 'center', 'top'],
														'distribute': ['between', 'right'],
														'space-a': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-h': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-v': ['xs', 's', 'm', 'l', 'xl', 'xxl'] } },
			{ block: 'pt-card', elem: 'header', mods: { 'align': ['center', 'right'],
														'space-a': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-h': ['xs', 's', 'm', 'l', 'xl', 'xxl'],
														'space-v': ['xs', 's', 'm', 'l', 'xl', 'xxl'] } },
			{ block: 'pt-card', elem: 'image', mods: { size: 'cover' } },
			{ block: 'pt-card', elem: 'play' },

			{ block: 'pt-form', mods: { border: 'all', shadow: 'cloud', view: 'default' } },
			{ block: 'pt-form', elem: 'control' },
			{ block: 'pt-form', elem: 'event' },
			{ block: 'pt-form', elem: 'item', mods: { border: ['all', 'bottom', 'top'],
													  distribute: ['between', 'default', 'right'],
													 'indent-a': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-b': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-h': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-l': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-r': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-t': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'indent-v': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-a': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-b': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-h': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-l': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-r': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-t': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'space-v': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													 'vertical-align': ['baseline', 'center', 'default'] } },
			{ block: 'pt-form', elem: 'label', mods: { 'width': ['default', 'inverse'] } },
			
			{ block: 'pt-icon-plus', mods: { distribute: 'between',
											'vertical-align': ['bottom', 'center', 'top'] } },
			{ block: 'pt-icon-plus', elem: 'block' },
			{ block: 'pt-icon-plus', elem: 'icon', mods: { 'indent-l': ['xxs', 'xs', 's', 'm', 'l'],
														   'indent-r': ['xxs', 'xs', 's', 'm', 'l'],
														   'offset': ['no'] } },

			{ block: 'pt-informer', mods: { border: ['all'],
											view: ['alert', 'default', 'normal', 'success', 'system', 'warning'] } },
			{ block: 'pt-informer', elem: 'action', mods: { 'align': ['center', 'right'],
															'space-a': ['s', 'm', 'l', 'xl', 'xxl'],
															'space-b': ['s', 'm', 'l', 'xl', 'xxl'],
															'space-h': ['s', 'm', 'l', 'xl', 'xxl'],
															'space-v': ['s', 'm', 'l', 'xl', 'xxl'] } },
			{ block: 'pt-informer', elem: 'col', mods: { 'align': ['center'] } },
			{ block: 'pt-informer', elem: 'content', mods: { 'distribute': ['between', 'center', 'default'],
															 'space-a': ['s', 'm', 'l', 'xl', 'xxl'],
															 'space-h': ['s', 'm', 'l', 'xl', 'xxl'],
															 'space-v': ['s', 'm', 'l', 'xl', 'xxl'] } },
			
			{ block: 'pt-list', mods: { border: ['all'],
										view: ['default', 'ghost'] } },
			{ block: 'pt-list', elem: 'item', mods: { 'border': ['bottom', 'top'],
													  'distribute': ['between', 'default'],
													  'indent-a': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-b': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-h': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-l': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-r': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-t': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'indent-v': ['xs', 's', 'm', 'l', 'xl', 'xxl', 'xxxl'],
													  'space-a': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-b': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-h': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-l': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-r': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-t': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'space-v': ['xxs', 'xs', 's', 'm', 'l', 'xl', 'xxl'],
													  'vertical-align': ['baseline', 'center', 'top'] } },

			{ block: 'pt-surface', view: ['soft', 'tone'] },
			{ block: 'pt-surface', elem: 'window' },
			{ block: 'pt-surface', elem: 'close', mods: { view: ['desktop', 'mobile'] } },
			{ block: 'pt-surface', elem: 'content', mods: { size: ['xs', 's', 'm', 'full'],
															'space-a': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-b': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-h': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-l': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-r': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-t': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'space-v': ['s', 'm', 'l', 'xl', 'xxl', 'xxxl', 'xxxxl'],
															'view': ['default'] } },

			{ block: 'pt-table', mods: { border: ['all'],
										'space-a': ['xs', 's', 'm', 'l'],
										'space-h': ['xs', 's', 'm', 'l'],
										'space-v': ['xs', 's', 'm', 'l'],
										'stripe': ['even', 'odd'],
										'view': ['default'] } },
			{ block: 'pt-table', elem: 'col', mods: { align: ['right'],
													  grow: ['evenly'],
													  width: ['5', '10', '15', '20', '25', '30', '35', '40', '45', '50', '55', '60', '65', '70', '75', '80', '85', '90', '95', '100'], } },
			{ block: 'pt-table', elem: 'row', mods: { border: ['bottom', 'top'],
													  status: ['alert', 'default', 'success', 'warning'],
													  view: ['head'] } },

			{ block: 'tpl-grid', mods: { 'col-gap': ['full', 'half', 'none', 'third', 'two-thirds'],
										 'columns': ['10', '12'],
										 'ratio': ['1-1-1-1-1-1', '1-1-1-1-1', '1-1-1-1', '1-1-1', '1-1'],
										 'row-gap': ['full', 'half', 'none', 'third', 'two-thirds'] } },
			{ block: 'tpl-grid', elem: 'fraction', mods: { 'col': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
														   's-col': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
														   'm-col': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
														   'l-col': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
														   'xl-col': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
														   'row': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'] } },

			{ block: 'tpl-layout', mods: { structure: ['10-90', '20-60-20', '30-70', '50-50', '70-30', '90-10', 'fold-25-50-25', 'fold-30-70', 'fold-50-50', 'fold-70-30', 'fold-100', 'unfold-25-50-25', 'unfold-30-70', 'unfold-50-50', 'unfold-70-30', 'unfold-100'] } },
			{ block: 'tpl-layout', elem: 'content' },
			{ block: 'tpl-layout', elem: 'heading' },
			{ block: 'tpl-layout', elem: 'panel' },
			{ block: 'tpl-layout', elem: 'section' },
			{ block: 'tpl-layout', elem: 'container', mods: { align: ['center'],
															  size: ['full', 'm', 's', 'xs'] } },
		]
	}
])